### ISSUE TITLE
ConfigureAwait as a developmentDependency

### ISSUE THREAD

**Issue by blankensteiner** [Fody/ConfigureAwait#104]
When creating libraries and wanting all awaits to be ConfigureAwait(false), the process is to install Fody and ConfigureAwait.Fody and then update the FodyWeavers.xml or use the assembly wide attribute.
This adds ConfigureAwait.Fody as a runtime dependency, even though in the case of using the xml-file, it only needs to be a developmentDependency.

Would you be open to creating a NuGet package (could be called ConfigureAwaitFalse.Fody), that is a developmentDependency and automatically setting all to false? Which meanings there is no need for the XML-file or using the assembly wide attribute. Just install the package and that is it.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by SimonCropp** [comment]
even if the package is marked as `developmentDependency`, you would still need the xml file. that is a requirement of Fody. one possibility is to use the `PackageReference` in the csproj instead of the xml file. but that would be a much more significant change and unlikely to happen in the short term
